### ISSUE TITLE
Scripted Tool Loader

### ISSUE THREAD

**Issue by 0x57e11a** [SMTheGuild/sm.interop#2]
It appears that the "Modded Tool Loader" tool does not show up in my tools list, any ideas about what's going on here?
![WEFVIlB 1](https://user-images.githubusercontent.com/29938460/107889374-f8b31d00-6ec6-11eb-95bf-5b459748f3eb.png)

**Comment by Xesau** [comment]
Thanks for reporting. This issue, among others, has been resolved in the latest update.
